# Generated by Django 4.0.4 on 2022-05-31 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notetodo',
            options={'verbose_name': 'заметка', 'verbose_name_plural': 'заметки'},
        ),
        migrations.AddField(
            model_name='notetodo',
            name='note_status',
            field=models.IntegerField(choices=[(0, 'Активно'), (1, 'Выполнено'), (2, 'Отложено')], default=0, verbose_name='Статус состояния'),
        ),
    ]
