# Generated by Django 4.0.4 on 2022-05-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_todo', '0002_alter_notetodo_options_notetodo_note_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetodo',
            name='due_to',
            field=models.DateField(verbose_name='До какого числа исполнить'),
        ),
    ]
