# Generated by Django 4.0.4 on 2022-05-31 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note_todo', '0003_alter_notetodo_due_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetodo',
            name='due_to',
            field=models.DateTimeField(verbose_name='До какого числа исполнить'),
        ),
    ]
